swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Definition for Risk Score Calcultion
  description: REST API that for calculating risk score for authentication requests
paths:
  /calculate:
    post:
      description: Method to obtain the calculated risk score an authentication request
      operationId: calculateRiskScore
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: authRequest
          in: body
          description: authentication request by the user
          required: true
          schema:
            $ref: '#/definitions/authRequest'
      responses:
        '200':
          description: Risk Score
          schema:
            $ref: '#/definitions/riskScore'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'

definitions:
  authRequest:
    type: object
    required:
      - username
      - userStoreDomain
      - tenantDomain
      - remoteIp
      - timestamp
      - inboundAuthType
      - serviceProvider
      - rememberMeEnabled
      - forceAuthEnabled
      - passiveAuthEnabled
      - identityProvider
      - stepAuthenticator
      - propertyBag

    properties:
      username:
        type: string
      userStoreDomain:
        type: string
      tenantDomain:
        type: string
      remoteIp:
        type: string
      timestamp:
        type: string
      inboundAuthType:
        type: string
      serviceProvider:
        type : string
      rememberMeEnabled:
        type : boolean
      forceAuthEnabled :
        type : boolean
      passiveAuthEnabled:
        type : boolean
      identityProvider :
        type : string
      stepAuthenticator :
        type : string
      propertyMap:
        type: object
        additionalProperties:
          type: string
  riskScore:
    type: object
    required:
      - score
    properties:
      score :
        type: integer
        format : int32
        default : 2
  errorModel:
    type: object
    required:
      - status
      - code
      - message
      - additionalDetails
    properties:
      status:
        type: string
      code:
        type: string
      message:
        type: string


